steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ticbot-359806/hello', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ticbot-359806/hello']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'ticbot-00001-zuf', '--image', 'gcr.io/ticbot-359806/hello', '--region', 'REGION']
images:
- gcr.io/ticbot-359806/hello